services:
  php:
    container_name: php-server
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  
  phpmyadmin:
    container_name: phpmyadmin-server
    image: phpmyadmin:5.2.2-apache
    ports:
      - "8080:80"
    environment:
      - PMA_PORT=3306
      - PMA_HOST=db
    depends_on:
      - db

  db:
    container_name: mysql-server
    image: mysql:8.4.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      # Only if you want to allow empty password for root user
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./db_data:/var/lib/mysql